import React, { createContext, useContext, useState } from 'react';

type Language = 'ja' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ja: {
    'nav.philosophy': 'PHILOSOPHY',
    'nav.menu': 'MENU',
    'nav.reviews': 'REVIEWS',
    'nav.instagram': 'INSTAGRAM',
    'nav.access': 'ACCESS',
    'hero.title1': 'NEXT',
    'hero.title2': 'STOP',
    'hero.title3': '心斎橋',
    'hero.kicker': 'RELOCATION',
    'hero.subtitle': '南森町から、心斎橋・三ッ寺会館1Fへ。\n移転準備のため、ただいま一時休業しています。',
    'hero.button': '新店舗を見る',
    'hero.tagline': 'Good food. Fair price. No compromise',
    'hero.scroll': 'SCROLL',
    'section.philosophy_label': 'OUR STORY',
    'section.menu_label': 'ORDER NOW',
    'section.reviews_label': 'VOICES',
    'section.access_label': 'VISIT US',
    'philosophy.title': 'PHILOSOPHY',
    'philosophy.headline': 'すべてに、納得感を。',
    'philosophy.pillars': '美味しさ　価格　ボリューム　サービス　空間',
    'philosophy.body': 'ひとつひとつに理由があり、食べ終わったあとに「ここを選んでよかった」と思ってもらえるバーガーショップを目指します。',
    'philosophy.closer': '大阪・心斎橋で、また会いましょう。',
    'philosophy.subtitle': 'シンプルだからこそ、美味い',
    'philosophy.beef': '100% AUSSIE BEEF',
    'philosophy.beef_desc': '厳選されたオーストラリア産牛肉を100%使用。冷凍パティは一切使わず、毎日新鮮な状態でご提供。',
    'philosophy.smash': 'SMASH TECHNIQUE',
    'philosophy.smash_desc': '高温の鉄板で一気にプレス。外はカリカリ、中はジューシー。アメリカで大人気の調理法を忠実に再現。',
    'philosophy.house': 'HOUSE-MADE',
    'philosophy.house_desc': 'ソース、トッピング、スパイスまですべて店内で手作り。化学調味料は一切使用していません。',
    'menu.title': 'MENU',
    'menu.subtitle': '※セットのみ（フライ＋ドリンク付き）',
    'menu.tag_classic': '定番',
    'menu.tag_popular': '人気NO.1',
    'menu.tag_authentic': '本格派',
    'menu.cheese_burger': 'CHEESE BURGER',
    'menu.cheese_burger_ja': 'チーズバーガー',
    'menu.cheese_burger_desc': '100%オージービーフを高温鉄板でスマッシュ。カリッと香ばしい焦げ目と、肉汁溢れるジューシーさ。とろけるチェダーチーズと自家製ソースが絶妙に絡む。キャラメライズオニオンとの相性抜群。シンプルだからこそ、素材の良さが際立つ定番の一品。',
    'menu.double_cheese': 'DOUBLE CHEESE burger',
    'menu.double_cheese_ja': 'ダブルチーズバーガー',
    'menu.double_cheese_desc': '【人気No.1】圧倒的な肉々しさを求めるなら、これ一択。パティ2枚×チーズ2枚の贅沢な構成。一口ごとに溢れ出す肉汁と、とろけるチーズの濃厚なハーモニー。ガッツリ食べたい時の最高の選択。満足度MAX保証。',
    'menu.hot_chicken': 'Nashville HOT CHICKEN',
    'menu.hot_chicken_ja': 'ナッシュビルホットチキン',
    'menu.hot_chicken_desc': '【本格派】アメリカ南部・ナッシュビル発祥の名物を忠実に再現。自家製スパイスブレンドで仕上げた、ジューシーなフライドチキン。カイエンペッパーの効いた辛さが、クセになる美味しさ。Plain（ソース無し）or Hot（激辛）でお好みの辛さを選択可能。',
    'menu.hamburger': 'HAMBURGER',
    'menu.hamburger_ja': 'ハンバーガー',
    'menu.hamburger_desc': '究極のシンプル。余計なものは何もいらない。新鮮なレタス、トマト、チーズ。スマッシュパティの旨味だけで勝負する潔さ。「これが本物のハンバーガーだ」と気づく瞬間。',
    'menu.bacon_lettuce': 'BACON LETTUCE burger',
    'menu.bacon_lettuce_ja': 'ベーコンレタスバーガー',
    'menu.bacon_lettuce_desc': 'こんがり焼き上げたベーコン。シャキシャキのグリーンリーフレタスが爽やかさを添える。ジューシーなパティとの絶妙なバランスを生む。',
    'menu.double_burger': 'DOUBLE hamBURGER',
    'menu.double_burger_ja': 'ダブルハンバーガー',
    'menu.double_burger_desc': 'チーズよりも、肉の旨味を堪能したいあなたへ。100%オージービーフのパティを2枚重ね。余計な味付けは一切なし。肉本来の深い味わいだけを追求。真の肉好きが選ぶ、ストレートな美味しさ。',
    'menu.thick_bacon': 'THICK BACON lettuce burger',
    'menu.thick_bacon_ja': '厚切りベーコンレタスバーガー',
    'menu.thick_bacon_desc': '「ベーコン好きのためのバーガー」を追求した一品。通常の倍以上の厚切りベーコンをたっぷり贅沢に。カリッと焼き上げた香ばしさと、肉厚な食べ応え。グリーンリーフの爽やかさが、濃厚な味わいを引き立てる。',
    'menu.junk_cheese': 'JUNK CHEESE',
    'menu.junk_cheese_ja': 'ジャンクチーズバーガー',
    'menu.junk_cheese_desc': '店内飲食のみ',
    'reviews.title': 'REVIEWS',
    'reviews.subtitle': '南森町時代 Google 4.7（83件）',
    'access.title': 'ACCESS',
    'access.subtitle': '心斎橋・三ッ寺会館1F',
    'access.closed_notice': '移転準備中。オープン日はInstagramでお知らせします。',
    'access.address': 'ADDRESS',
    'access.address_value': '大阪府大阪市中央区西心斎橋2-9-5　三ッ寺会館1F',
    'access.station': 'STATION',
    'access.station_value': '心斎橋駅 徒歩圏内',
    'access.phone': 'PHONE',
    'access.phone_value': '080-1520-0694',
    'access.hours': 'HOURS',
    'access.hours_weekday': '営業時間はオープン後に公開',
    'access.hours_weekend': '最新情報はInstagramへ',
    'access.map': 'Google Mapsで見る',
    'access.navigation': 'ルートを案内',
    'access.ubereats': 'オープン情報を見る',
    'footer.title': 'geezer',
    'footer.subtitle': 'Good food. Fair price. No compromise',
    'footer.copyright': '© 2026 geezer. All rights reserved.',
    'instagram.subtitle': '公式Instagram',
    'instagram.follow': 'フォローする',
    'instagram.view': 'Instagramで見る',
    'ingredients.view': '使用材料を見る',
    'ingredients.title': '使用材料',
    'ingredients.note': '○ は使用材料の目安です。仕入れ状況により変更となる場合があります。',
    'ingredients.col_name': '材料',
    'ingredients.col_amount': '分量',
    'ingredients.col_note': '備考',
    'ingredients.allergens': 'アレルギー情報（参考）',
    'ingredients.disclaimer': '※ アレルギー体質の方はスタッフまでお声がけください。表示は参考情報です。',
    'ingredients.qr_title': 'QRコード',
    'ingredients.qr_desc': '店内POPやメニュー表に掲載するQRコードです。お客様が読み取るとこのページが開きます。',
    'ingredients.qr_alt': '材料詳細ページへのQRコード',
    'ingredients.print_qr': 'QR印刷用ページ',
    'ingredients.back_menu': 'メニューに戻る',
    'ingredients.not_found': 'メニューが見つかりませんでした。',
    'ingredients.print': '印刷する',
    'ingredients.scan': 'スマホで読み取って材料を確認',
    'sides.title': 'SIDE MENU',
    'drinks.title': 'SOFT DRINK & ALCOHOL',
    'drinks.soft_title': 'SOFT DRINK',
    'drinks.alcohol_title': 'ALCOHOL',
    'drinks.alcohol': 'ALC',
    'drinks.note': 'セットドリンクをお選びいただけます。＋400円でお酒（アルコール類）への変更も可能です。なお、単品ドリンクは400円、お酒は600円となります。',
    'drinks.brand_note': '※仕入れ状況により、掲載と異なるブランドをご提供する場合がございます。',
    'sauces.title': 'DIPPING SAUCE',
    'payment.title': 'PAYMENT',
    'payment.subtitle': 'お支払い方法',
    'payment.cash': '現金 OK',
    'payment.brands_alt': '決済対応ブランド一覧',
    'payment.note': '※ PiTaPaは除く。対応状況は店舗により異なる場合があります。',
  },
  en: {
    'nav.philosophy': 'PHILOSOPHY',
    'nav.menu': 'MENU',
    'nav.reviews': 'REVIEWS',
    'nav.instagram': 'INSTAGRAM',
    'nav.access': 'ACCESS',
    'hero.title1': 'NEXT',
    'hero.title2': 'STOP',
    'hero.title3': 'SHINSAIBASHI',
    'hero.kicker': 'RELOCATION',
    'hero.subtitle': 'Moving from Minamimorimachi to Mitsutera Kaikan 1F, Shinsaibashi.\nTemporarily closed while we get the new shop ready.',
    'hero.button': 'See the new location',
    'hero.tagline': 'Good food. Fair price. No compromise',
    'hero.scroll': 'SCROLL',
    'section.philosophy_label': 'OUR STORY',
    'section.menu_label': 'ORDER NOW',
    'section.reviews_label': 'VOICES',
    'section.access_label': 'VISIT US',
    'philosophy.title': 'PHILOSOPHY',
    'philosophy.headline': 'Conviction in everything.',
    'philosophy.pillars': 'Flavor · Price · Volume · Service · Space',
    'philosophy.body': 'Every choice has a reason. We want you to leave thinking, “I’m glad I picked this place.”',
    'philosophy.closer': 'See you in Shinsaibashi, Osaka.',
    'philosophy.subtitle': 'Simple — that\'s why it tastes so good',
    'philosophy.beef': '100% AUSSIE BEEF',
    'philosophy.beef_desc': 'We use carefully selected 100% Australian beef. No frozen patties — ever. Served fresh every day.',
    'philosophy.smash': 'SMASH TECHNIQUE',
    'philosophy.smash_desc': 'Pressed hard on a high-heat griddle. Crispy crust, juicy center. The smash technique that took America by storm, done right.',
    'philosophy.house': 'HOUSE-MADE',
    'philosophy.house_desc': 'Sauces, toppings, and spices — all made in-house. No artificial seasonings.',
    'menu.title': 'MENU',
    'menu.subtitle': '*Set only (Fries + Drink included)',
    'menu.tag_classic': 'CLASSIC',
    'menu.tag_popular': 'NO.1',
    'menu.tag_authentic': 'AUTHENTIC',
    'menu.cheese_burger': 'CHEESE BURGER',
    'menu.cheese_burger_ja': 'Cheese Burger',
    'menu.cheese_burger_desc': '100% Aussie beef smashed on a blazing-hot griddle. A crisp, savory crust with a juicy, flavor-packed center. Melted cheddar and house-made sauce wrap around every bite. Pairs perfectly with caramelized onions. Simple — so the ingredients shine. Our signature classic.',
    'menu.double_cheese': 'DOUBLE CHEESE burger',
    'menu.double_cheese_ja': 'Double Cheese Burger',
    'menu.double_cheese_desc': '[#1 Favorite] If you want serious beef, this is the one. Two patties × two slices of cheese. Juices pour out with every bite, locked in with rich melted cheese. The ultimate pick when you\'re hungry. Satisfaction guaranteed.',
    'menu.hot_chicken': 'Nashville HOT CHICKEN',
    'menu.hot_chicken_ja': 'Nashville Hot Chicken',
    'menu.hot_chicken_desc': '[Authentic] Faithfully recreating the Southern U.S. classic born in Nashville. Juicy fried chicken finished with our house spice blend. Cayenne heat that\'s addictive. Choose Plain (no sauce) or Hot (extra spicy).',
    'menu.hamburger': 'HAMBURGER',
    'menu.hamburger_ja': 'Hamburger',
    'menu.hamburger_desc': 'Ultimate simplicity. Nothing extra. Fresh lettuce, tomato, and cheese. Just the smash patty\'s pure flavor — no distractions. The moment you realize: this is a real hamburger.',
    'menu.bacon_lettuce': 'BACON LETTUCE burger',
    'menu.bacon_lettuce_ja': 'Bacon Lettuce Burger',
    'menu.bacon_lettuce_desc': 'Crispy, well-browned bacon. Crunchy green leaf lettuce for freshness. A perfectly balanced bite with the juicy smash patty.',
    'menu.double_burger': 'DOUBLE hamBURGER',
    'menu.double_burger_ja': 'Double Hamburger',
    'menu.double_burger_desc': 'For those who want the beef itself, more than the cheese. Two 100% Aussie beef patties, stacked. No extra seasoning. Just the deep, true flavor of the meat. Straight-up delicious — for real meat lovers.',
    'menu.thick_bacon': 'THICK BACON lettuce burger',
    'menu.thick_bacon_ja': 'Thick-Cut Bacon Lettuce Burger',
    'menu.thick_bacon_desc': 'Built for bacon lovers. Generously loaded with thick-cut bacon — more than twice the usual cut. Crispy, fragrant, and seriously meaty. Green leaf lettuce keeps the rich flavors bright.',
    'menu.junk_cheese': 'JUNK CHEESE',
    'menu.junk_cheese_ja': 'Junk Cheese Burger',
    'menu.junk_cheese_desc': 'Dine-in only',
    'reviews.title': 'REVIEWS',
    'reviews.subtitle': 'Minamimorimachi era — Google 4.7 (83 reviews)',
    'access.title': 'ACCESS',
    'access.subtitle': 'Mitsutera Kaikan 1F, Shinsaibashi',
    'access.closed_notice': 'Preparing the move. Opening date will be announced on Instagram.',
    'access.address': 'ADDRESS',
    'access.address_value': 'Mitsutera Kaikan 1F, 2-9-5 Nishishinsaibashi, Chuo-ku, Osaka',
    'access.station': 'STATION',
    'access.station_value': 'Shinsaibashi Station — walking distance',
    'access.phone': 'PHONE',
    'access.phone_value': '080-1520-0694',
    'access.hours': 'HOURS',
    'access.hours_weekday': 'Hours announced after we open',
    'access.hours_weekend': 'Follow Instagram for updates',
    'access.map': 'View on Google Maps',
    'access.navigation': 'Get directions',
    'access.ubereats': 'Get opening updates',
    'footer.title': 'geezer',
    'footer.subtitle': 'Good food. Fair price. No compromise',
    'footer.copyright': '© 2026 geezer. All rights reserved.',
    'instagram.subtitle': 'Our Instagram',
    'instagram.follow': 'Follow us',
    'instagram.view': 'View on Instagram',
    'ingredients.view': 'View ingredients',
    'ingredients.title': 'Ingredients',
    'ingredients.note': '○ marks ingredients used. Items may change with supply.',
    'ingredients.col_name': 'Ingredient',
    'ingredients.col_amount': 'Amount',
    'ingredients.col_note': 'Note',
    'ingredients.allergens': 'Allergens (reference)',
    'ingredients.disclaimer': 'Please ask staff if you have allergies. This is for reference only.',
    'ingredients.qr_title': 'QR Code',
    'ingredients.qr_desc': 'Print this QR on table tents or menus. Guests scan to open this page.',
    'ingredients.qr_alt': 'QR code to ingredient details',
    'ingredients.print_qr': 'Print QR page',
    'ingredients.back_menu': 'Back to menu',
    'ingredients.not_found': 'Menu item not found.',
    'ingredients.print': 'Print',
    'ingredients.scan': 'Scan to view ingredients',
    'sides.title': 'SIDE MENU',
    'drinks.title': 'SOFT DRINK & ALCOHOL',
    'drinks.soft_title': 'SOFT DRINK',
    'drinks.alcohol_title': 'ALCOHOL',
    'drinks.alcohol': 'ALC',
    'drinks.note': 'Please choose a set drink. Upgrade to alcohol for +¥400. Single soft drinks are ¥400; alcoholic drinks are ¥600.',
    'drinks.brand_note': '*Brands may differ from those shown depending on supply.',
    'sauces.title': 'DIPPING SAUCE',
    'payment.title': 'PAYMENT',
    'payment.subtitle': 'Payment methods',
    'payment.cash': 'Cash accepted',
    'payment.brands_alt': 'Accepted payment brands',
    'payment.note': '*PiTaPa not accepted. Available methods may vary.',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('ja');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['ja']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
